{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "portalui.serviceAccountName" . }}
  labels:
{{ include "portalui.labels" . | indent 4 }}
{{- end -}}
